"""Application services coordinating GUI-independent models and file readers."""

from .project_files import ProjectFileService
from .correction import apply_correction, corrected_name
from .diffraction import (
    calculate_reflections,
    d_spacing_from_two_theta,
    format_hkl_family,
    gaussian_powder_profile,
)
from .peak_fitting import fit_gaussian_peak
from .pole_figure import (
    align_to_z,
    available_reflections,
    base_orientation,
    calculated_intensity_by_spacing,
    euler_matrix,
    format_hkl,
    group_coincident_poles,
    in_plane_alignment,
    marker_sizes_by_d,
    matrix_to_euler,
    place_label_boxes,
    pole_display_orientation,
    pole_display_position,
    pole_plot_coordinates,
    pole_plot_to_sphere,
    project_reflections,
    projection_code,
    rotation_axis_angle,
    rotation_between,
    rotation_x,
    rotation_y,
    rotation_z,
)
from .reference_peaks import read_reference_peaks, write_reference_peaks
from .substrate_compare import (
    ComparisonPlotData,
    ComparisonPlotSeries,
    comparison_axis_label,
    comparison_axis_uses_degrees,
    comparison_palette,
    comparison_preset_for,
    prepare_comparison_plot,
    transform_comparison_y,
)

__all__ = [
    "ProjectFileService",
    "ComparisonPlotData",
    "ComparisonPlotSeries",
    "apply_correction",
    "align_to_z",
    "available_reflections",
    "base_orientation",
    "calculated_intensity_by_spacing",
    "comparison_axis_label",
    "comparison_axis_uses_degrees",
    "comparison_palette",
    "comparison_preset_for",
    "corrected_name",
    "calculate_reflections",
    "d_spacing_from_two_theta",
    "euler_matrix",
    "fit_gaussian_peak",
    "format_hkl_family",
    "format_hkl",
    "gaussian_powder_profile",
    "group_coincident_poles",
    "in_plane_alignment",
    "marker_sizes_by_d",
    "matrix_to_euler",
    "place_label_boxes",
    "pole_display_orientation",
    "pole_display_position",
    "pole_plot_coordinates",
    "pole_plot_to_sphere",
    "project_reflections",
    "projection_code",
    "prepare_comparison_plot",
    "read_reference_peaks",
    "rotation_between",
    "rotation_axis_angle",
    "rotation_x",
    "rotation_y",
    "rotation_z",
    "transform_comparison_y",
    "write_reference_peaks",
]
